# Generated by Django 5.2.5 on 2025-09-25 13:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinaria', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionChatIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_chat_ia', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Sesión Chat IA',
                'verbose_name_plural': 'Sesiones Chat IA',
                'ordering': ['-fecha_ultima_actividad'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChatIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario'), ('ia', 'Asistente IA'), ('sistema', 'Sistema')], max_length=10)),
                ('contenido', models.TextField()),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tiempo_procesamiento', models.DurationField(blank=True, null=True)),
                ('tokens_utilizados', models.IntegerField(blank=True, null=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='ia_assistant.sesionchatia')),
            ],
            options={
                'verbose_name': 'Mensaje Chat IA',
                'verbose_name_plural': 'Mensajes Chat IA',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConocimientoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('maquinaria', 'Maquinaria y Equipos'), ('mantenimiento', 'Mantenimiento'), ('seguridad', 'Seguridad Industrial'), ('procesos', 'Procesos de Manufactura'), ('diagnostico', 'Diagnóstico de Fallas'), ('normatividad', 'Normatividad y Estándares')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('palabras_clave', models.JSONField(default=list)),
                ('vectores_embedding', models.JSONField(blank=True, default=list)),
                ('relevancia_score', models.DecimalField(decimal_places=4, default=1.0, help_text='Score de relevancia para el sistema de IA', max_digits=5)),
                ('veces_utilizado', models.IntegerField(default=0)),
                ('ultima_utilizacion', models.DateTimeField(blank=True, null=True)),
                ('efectividad_promedio', models.DecimalField(blank=True, decimal_places=2, help_text='Efectividad promedio según feedback de usuarios', max_digits=5, null=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Conocimiento IA',
                'verbose_name_plural': 'Base de Conocimiento IA',
                'ordering': ['-relevancia_score', '-fecha_actualizacion'],
                'indexes': [models.Index(fields=['categoria'], name='ia_assistan_categor_bc4ea8_idx'), models.Index(fields=['activo'], name='ia_assistan_activo_e7989d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsultaIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_consulta', models.CharField(choices=[('diagnostico', 'Diagnóstico de Problema'), ('mantenimiento', 'Recomendación de Mantenimiento'), ('optimizacion', 'Optimización de Procesos'), ('prediccion', 'Predicción de Fallas'), ('general', 'Consulta General')], default='general', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('consulta_texto', models.TextField()),
                ('contexto_adicional', models.JSONField(blank=True, default=dict)),
                ('respuesta_ia', models.TextField(blank=True)),
                ('confianza_respuesta', models.DecimalField(blank=True, decimal_places=2, help_text='Nivel de confianza de la IA (0-100%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recomendaciones', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completada', 'Completada'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('tiempo_procesamiento', models.DurationField(blank=True, null=True)),
                ('calificacion', models.IntegerField(blank=True, help_text='Calificación de 1 a 5 estrellas', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_texto', models.TextField(blank=True)),
                ('util', models.BooleanField(blank=True, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_feedback', models.DateTimeField(blank=True, null=True)),
                ('archivos_consulta', models.JSONField(blank=True, default=list)),
                ('imagenes_diagnostico', models.JSONField(blank=True, default=list)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_ia', to='maquinaria.maquina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_ia', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Consulta IA',
                'verbose_name_plural': 'Consultas IA',
                'ordering': ['-fecha_consulta'],
                'indexes': [models.Index(fields=['usuario', '-fecha_consulta'], name='ia_assistan_usuario_cc3a93_idx'), models.Index(fields=['estado'], name='ia_assistan_estado_00c266_idx'), models.Index(fields=['tipo_consulta'], name='ia_assistan_tipo_co_7758d9_idx'), models.Index(fields=['maquina'], name='ia_assistan_maquina_246376_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrediccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prediccion', models.CharField(choices=[('falla_inminente', 'Falla Inminente'), ('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('optimizacion_uso', 'Optimización de Uso'), ('vida_util', 'Estimación Vida Útil'), ('costo_mantenimiento', 'Predicción de Costos')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada_evento', models.DateTimeField()),
                ('probabilidad', models.DecimalField(decimal_places=2, help_text='Probabilidad del evento (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confianza', models.DecimalField(decimal_places=2, help_text='Nivel de confianza de la predicción (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('datos_entrada', models.JSONField(default=dict)),
                ('modelo_ia_utilizado', models.CharField(blank=True, max_length=100)),
                ('version_modelo', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cumplida', 'Cumplida'), ('descartada', 'Descartada'), ('en_seguimiento', 'En Seguimiento')], default='activa', max_length=20)),
                ('fecha_cumplimiento', models.DateTimeField(blank=True, null=True)),
                ('precision_real', models.DecimalField(blank=True, decimal_places=2, help_text='Precisión real después de validar la predicción', max_digits=5, null=True)),
                ('acciones_recomendadas', models.JSONField(blank=True, default=list)),
                ('costo_estimado_accion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ahorro_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_ia', to='maquinaria.maquina')),
            ],
            options={
                'verbose_name': 'Predicción IA',
                'verbose_name_plural': 'Predicciones IA',
                'ordering': ['-fecha_prediccion', '-probabilidad'],
                'indexes': [models.Index(fields=['maquina', '-fecha_prediccion'], name='ia_assistan_maquina_6d0072_idx'), models.Index(fields=['tipo_prediccion'], name='ia_assistan_tipo_pr_c4e7a6_idx'), models.Index(fields=['estado'], name='ia_assistan_estado_ab5e52_idx'), models.Index(fields=['fecha_estimada_evento'], name='ia_assistan_fecha_e_2f08c9_idx')],
            },
        ),
    ]
