# Generated by Django 5.2.5 on 2025-09-25 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinaria', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('tipo_valor', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número Entero'), ('float', 'Número Decimal'), ('boolean', 'Verdadero/Falso'), ('json', 'JSON'), ('date', 'Fecha'), ('datetime', 'Fecha y Hora'), ('email', 'Correo Electrónico'), ('url', 'URL')], default='string', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(default='general', max_length=50)),
                ('publico', models.BooleanField(default=False)),
                ('modificable', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['categoria', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('contador', 'Contador'), ('grafico_linea', 'Gráfico de Líneas'), ('grafico_barra', 'Gráfico de Barras'), ('grafico_pastel', 'Gráfico de Pastel'), ('tabla', 'Tabla'), ('mapa', 'Mapa'), ('calendario', 'Calendario'), ('lista', 'Lista'), ('estado', 'Indicador de Estado'), ('progreso', 'Barra de Progreso')], max_length=20)),
                ('configuracion', models.JSONField(default=dict)),
                ('css_personalizado', models.TextField(blank=True)),
                ('javascript_personalizado', models.TextField(blank=True)),
                ('fuente_datos', models.CharField(blank=True, max_length=200)),
                ('query_personalizada', models.TextField(blank=True)),
                ('parametros_datos', models.JSONField(blank=True, default=dict)),
                ('cache_duracion_segundos', models.IntegerField(default=300)),
                ('datos_cache', models.JSONField(blank=True, default=dict)),
                ('cache_actualizado', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('requiere_permisos', models.JSONField(blank=True, default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets_creados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('debug', 'Debug'), ('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='info', max_length=10)),
                ('modulo', models.CharField(choices=[('usuarios', 'Usuarios'), ('maquinaria', 'Maquinaria'), ('reportes', 'Reportes'), ('ia_assistant', 'Asistente IA'), ('documentos', 'Documentos'), ('sistema', 'Sistema'), ('api', 'API')], default='sistema', max_length=20)),
                ('sesion_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objeto_tipo', models.CharField(blank=True, max_length=50)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('tiempo_ejecucion', models.DurationField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='components__timesta_e4e3ff_idx'), models.Index(fields=['usuario', 'timestamp'], name='components__usuario_bd155a_idx'), models.Index(fields=['modulo', 'timestamp'], name='components__modulo_7638cc_idx'), models.Index(fields=['nivel'], name='components__nivel_c33db9_idx'), models.Index(fields=['accion'], name='components__accion_13a977_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='bi-star', max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('abrir_nueva_ventana', models.BooleanField(default=False)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_personalizados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Menú Personalizado',
                'verbose_name_plural': 'Menús Personalizados',
                'ordering': ['usuario', 'orden', 'nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('system', 'Sistema')], default='info', max_length=10)),
                ('icono', models.CharField(default='bi-bell', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('leida', 'Leída'), ('archivada', 'Archivada')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_archivado', models.DateTimeField(blank=True, null=True)),
                ('requiere_accion', models.BooleanField(default=False)),
                ('url_accion', models.URLField(blank=True)),
                ('texto_accion', models.CharField(blank=True, max_length=100)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('enviado_por_sistema', models.BooleanField(default=True)),
                ('alerta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maquinaria.alertamaquina')),
                ('maquina_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maquinaria.maquina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='components__usuario_c4d189_idx'), models.Index(fields=['fecha_creacion'], name='components__fecha_c_890ec2_idx'), models.Index(fields=['tipo'], name='components__tipo_373899_idx')],
            },
        ),
    ]
