# Generated by Django 5.2.5 on 2025-09-25 13:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinaria', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('template_path', models.CharField(blank=True, max_length=200)),
                ('parametros_requeridos', models.JSONField(default=list)),
                ('formato_salida', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipos de Reporte',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetricasRendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], max_length=10)),
                ('centro_formacion', models.CharField(max_length=200)),
                ('total_maquinas', models.IntegerField(default=0)),
                ('maquinas_operativas', models.IntegerField(default=0)),
                ('maquinas_mantenimiento', models.IntegerField(default=0)),
                ('maquinas_reparacion', models.IntegerField(default=0)),
                ('maquinas_fuera_servicio', models.IntegerField(default=0)),
                ('eficiencia_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('horas_uso_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_disponibles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tiempo_inactividad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mantenimientos_programados', models.IntegerField(default=0)),
                ('mantenimientos_completados', models.IntegerField(default=0)),
                ('mantenimientos_pendientes', models.IntegerField(default=0)),
                ('tiempo_promedio_reparacion', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('costo_mantenimiento_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('costo_reparaciones', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_maquinaria_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('alertas_generadas', models.IntegerField(default=0)),
                ('alertas_resueltas', models.IntegerField(default=0)),
                ('alertas_criticas', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('actualizado_por_sistema', models.BooleanField(default=True)),
                ('categoria_maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maquinaria.categoriamaquina')),
            ],
            options={
                'verbose_name': 'Métricas de Rendimiento',
                'verbose_name_plural': 'Métricas de Rendimiento',
                'ordering': ['-fecha', 'centro_formacion'],
                'indexes': [models.Index(fields=['fecha', 'periodo'], name='reportes_me_fecha_278b2e_idx'), models.Index(fields=['centro_formacion'], name='reportes_me_centro__f70333_idx'), models.Index(fields=['categoria_maquina'], name='reportes_me_categor_25ade6_idx')],
                'unique_together': {('fecha', 'periodo', 'centro_formacion', 'categoria_maquina')},
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('parametros', models.JSONField(default=dict)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('centros_formacion', models.JSONField(blank=True, default=list)),
                ('categorias_maquina', models.JSONField(blank=True, default=list)),
                ('estados_maquina', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('tiempo_procesamiento', models.DurationField(blank=True, null=True)),
                ('archivo_resultado', models.FileField(blank=True, null=True, upload_to='reportes/resultados/')),
                ('url_descarga', models.URLField(blank=True)),
                ('tamaño_archivo', models.BigIntegerField(blank=True, null=True)),
                ('total_registros', models.IntegerField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('logs_procesamiento', models.JSONField(blank=True, default=list)),
                ('veces_descargado', models.IntegerField(default=0)),
                ('fecha_ultima_descarga', models.DateTimeField(blank=True, null=True)),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_solicitados', to='usuarios.usuario')),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportes.tiporeporte')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['usuario_solicitante', '-fecha_solicitud'], name='reportes_re_usuario_bf1e5a_idx'), models.Index(fields=['estado'], name='reportes_re_estado_e3b4c6_idx'), models.Index(fields=['tipo_reporte'], name='reportes_re_tipo_re_f5c3ef_idx')],
            },
        ),
    ]
