# Generated by Django 5.2.5 on 2025-09-25 13:17

import django.core.validators
import django.db.models.deletion
import documentos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinaria', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('extensiones_permitidas', models.JSONField(default=list)),
                ('tamaño_maximo_mb', models.IntegerField(default=50)),
                ('icono', models.CharField(default='bi-file-text', max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='bi-folder', max_length=50)),
                ('color', models.CharField(default='#ffc107', max_length=7)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='documentos.categoriadocumento')),
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documento',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to=documentos.models.documento_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'xlsx', 'xls', 'ppt', 'pptx'])])),
                ('tamaño_archivo', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('palabras_clave', models.JSONField(blank=True, default=list)),
                ('autor_original', models.CharField(blank=True, max_length=200)),
                ('nivel_acceso', models.CharField(choices=[('publico', 'Público'), ('interno', 'Interno'), ('confidencial', 'Confidencial'), ('restringido', 'Restringido')], default='interno', max_length=15)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('publicado', 'Publicado'), ('archivado', 'Archivado'), ('obsoleto', 'Obsoleto')], default='borrador', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('total_descargas', models.IntegerField(default=0)),
                ('total_visualizaciones', models.IntegerField(default=0)),
                ('ultima_descarga', models.DateTimeField(blank=True, null=True)),
                ('contenido_texto', models.TextField(blank=True)),
                ('indices_busqueda', models.JSONField(blank=True, default=dict)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.categoriadocumento')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_creados', to='usuarios.usuario')),
                ('maquina_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='maquinaria.maquina')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_modificados', to='usuarios.usuario')),
                ('usuarios_acceso', models.ManyToManyField(blank=True, related_name='documentos_acceso', to='usuarios.usuario')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['estado'], name='documentos__estado_c5e9bd_idx'), models.Index(fields=['categoria'], name='documentos__categor_2da153_idx'), models.Index(fields=['tipo_documento'], name='documentos__tipo_do_7b089c_idx'), models.Index(fields=['creado_por'], name='documentos__creado__f5fffa_idx'), models.Index(fields=['nivel_acceso'], name='documentos__nivel_a_95537c_idx'), models.Index(fields=['maquina_relacionada'], name='documentos__maquina_ee4a6f_idx')],
            },
        ),
    ]
