# Generated by Django 5.2.5 on 2025-09-25 13:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='bi-gear', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Máquina',
                'verbose_name_plural': 'Categorías de Máquinas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('contacto_telefono', models.CharField(max_length=20)),
                ('contacto_email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('sitio_web', models.URLField(blank=True)),
                ('calificacion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('operativa', 'Operativa'), ('mantenimiento', 'En Mantenimiento'), ('reparacion', 'En Reparación'), ('fuera_servicio', 'Fuera de Servicio'), ('retirada', 'Retirada')], default='disponible', max_length=20)),
                ('condicion', models.CharField(choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala'), ('critica', 'Crítica')], default='excelente', max_length=20)),
                ('especificaciones_tecnicas', models.TextField(blank=True)),
                ('capacidad', models.CharField(blank=True, max_length=200)),
                ('potencia', models.CharField(blank=True, max_length=100)),
                ('voltaje', models.CharField(blank=True, max_length=50)),
                ('dimensiones', models.CharField(blank=True, max_length=100)),
                ('peso', models.CharField(blank=True, max_length=50)),
                ('ubicacion', models.CharField(max_length=200)),
                ('centro_formacion', models.CharField(max_length=200)),
                ('ambiente_formacion', models.CharField(blank=True, max_length=200)),
                ('fecha_adquisicion', models.DateField()),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('numero_factura', models.CharField(blank=True, max_length=100)),
                ('garantia_meses', models.IntegerField(default=12)),
                ('horas_uso_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_uso_mes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('eficiencia', models.DecimalField(decimal_places=2, default=100, help_text='Porcentaje de eficiencia', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('frecuencia_mantenimiento_dias', models.IntegerField(default=90)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinaria/imagenes/')),
                ('manual_pdf', models.FileField(blank=True, null=True, upload_to='maquinaria/manuales/')),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='maquinaria/fichas/')),
                ('observaciones', models.TextField(blank=True)),
                ('qr_code', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maquinaria.categoriamaquina')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_creadas', to='usuarios.usuario')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_asignadas', to='usuarios.usuario')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquinaria.proveedor')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['codigo_inventario'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('creacion', 'Creación'), ('mantenimiento', 'Mantenimiento'), ('reparacion', 'Reparación'), ('cambio_estado', 'Cambio de Estado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_responsable', 'Cambio de Responsable'), ('actualizacion', 'Actualización de Datos'), ('inspeccion', 'Inspección')], max_length=20)),
                ('descripcion', models.TextField()),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('costo_asociado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('archivos_adjuntos', models.JSONField(blank=True, default=list)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='maquinaria.maquina')),
            ],
            options={
                'verbose_name': 'Historial de Máquina',
                'verbose_name_plural': 'Historiales de Máquinas',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['maquina', '-fecha_evento'], name='maquinaria__maquina_f700b3_idx'), models.Index(fields=['tipo_evento'], name='maquinaria__tipo_ev_93247b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mantenimiento', 'Mantenimiento Programado'), ('reparacion', 'Reparación Urgente'), ('eficiencia', 'Baja Eficiencia'), ('uso_excesivo', 'Uso Excesivo'), ('garantia', 'Garantía por Vencer'), ('inspeccion', 'Inspección Requerida')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_resolucion', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_creadas', to='usuarios.usuario')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to='usuarios.usuario')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='maquinaria.maquina')),
            ],
            options={
                'verbose_name': 'Alerta de Máquina',
                'verbose_name_plural': 'Alertas de Máquinas',
                'ordering': ['-fecha_creacion', '-prioridad'],
                'indexes': [models.Index(fields=['estado'], name='maquinaria__estado_9224d1_idx'), models.Index(fields=['prioridad'], name='maquinaria__priorid_6ab393_idx'), models.Index(fields=['tipo'], name='maquinaria__tipo_c92584_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['codigo_inventario'], name='maquinaria__codigo__25a280_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['estado'], name='maquinaria__estado_5bcca8_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['categoria'], name='maquinaria__categor_39373a_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['centro_formacion'], name='maquinaria__centro__dcb72f_idx'),
        ),
    ]
