# Generated by Django 5.2.5 on 2025-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmaquina',
            name='tipo_evento',
            field=models.CharField(choices=[('creacion', 'Creación'), ('mantenimiento', 'Mantenimiento'), ('reparacion', 'Reparación'), ('cambio_estado', 'Cambio de Estado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_responsable', 'Cambio de Responsable'), ('actualizacion', 'Actualización de Datos'), ('inspeccion', 'Inspección'), ('alerta_creada', 'Alerta Creada'), ('eliminacion', 'Eliminación')], max_length=20),
        ),
    ]
