# Generated by Django 5.2.5 on 2025-09-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0003_alter_historialmaquina_tipo_evento'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo'), ('urgente', 'Urgente'), ('emergencia', 'Emergencia')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica'), ('emergencia', 'Emergencia')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('postergado', 'Postergado')], default='programado', max_length=20)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('duracion_estimada', models.DurationField(help_text='Duración estimada en formato HH:MM:SS')),
                ('duracion_real', models.DurationField(blank=True, null=True)),
                ('componentes_revisar', models.JSONField(default=list, help_text='Lista de componentes a revisar')),
                ('herramientas_necesarias', models.JSONField(default=list, help_text='Herramientas necesarias')),
                ('repuestos_necesarios', models.JSONField(default=list, help_text='Repuestos necesarios')),
                ('procedimientos', models.TextField(blank=True, help_text='Procedimientos paso a paso')),
                ('trabajo_realizado', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('problemas_encontrados', models.TextField(blank=True)),
                ('repuestos_utilizados', models.JSONField(default=list)),
                ('tiempo_parada', models.DurationField(blank=True, help_text='Tiempo que la máquina estuvo parada', null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_repuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('horas_operacion_siguiente', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_creados', to='usuarios.usuario')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='maquinaria.maquina')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to='usuarios.usuario')),
                ('tecnico_realizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Mantenimiento Programado',
                'verbose_name_plural': 'Mantenimientos Programados',
                'ordering': ['fecha_programada'],
                'indexes': [models.Index(fields=['fecha_programada'], name='maquinaria__fecha_p_b32647_idx'), models.Index(fields=['estado'], name='maquinaria__estado_2beffd_idx'), models.Index(fields=['tipo'], name='maquinaria__tipo_a9374c_idx'), models.Index(fields=['prioridad'], name='maquinaria__priorid_46a24e_idx')],
            },
        ),
    ]
